version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_cordillera
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cordillera_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Aquí está la persistencia exigida por la rúbrica

  api-ventas:
    # REEMPLAZA LA LÍNEA DE ABAJO CON LA URI DE TU REPOSITORIO ECR DE VENTAS
    image: 960261614846.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
    container_name: backend_ventas
    ports:
      - "8080:8080"
    depends_on:
      - db

  api-despachos:
    # REEMPLAZA LA LÍNEA DE ABAJO CON LA URI DE TU REPOSITORIO ECR DE DESPACHOS
    image: 960261614846.dkr.ecr.us-east-1.amazonaws.com/back-despachos:latest
    container_name: backend_despachos
    ports:
      - "8081:8080" # Lo exponemos en el 8081 para que no choque con el de ventas
    depends_on:
      - db

volumes:
  db_data: