name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: innovatech-cluster
  
  TASK_DEF_VENTAS: ventas-task
  ECS_SERVICE_VENTAS: servicio-ventas
  CONTAINER_NAME_VENTAS: back-ventas
  
  TASK_DEF_DESPACHOS: despachos-task
  ECS_SERVICE_DESPACHOS: servicio-despachos
  CONTAINER_NAME_DESPACHOS: back-despachos

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Ventas image to Amazon ECR
      id: build-image-ventas
      run: |
        docker build -t 674415805593.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest ./back-Ventas_SpringBoot/Springboot-API-REST
        docker push 674415805593.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest
        echo "image=674415805593.dkr.ecr.us-east-1.amazonaws.com/back-ventas:latest" >> $GITHUB_OUTPUT

    - name: Build, tag, and push Despachos image to Amazon ECR
      id: build-image-despachos
      run: |
        docker build -t 674415805593.dkr.ecr.us-east-1.amazonaws.com/back-despachos:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push 674415805593.dkr.ecr.us-east-1.amazonaws.com/back-despachos:latest
        echo "image=674415805593.dkr.ecr.us-east-1.amazonaws.com/back-despachos:latest" >> $GITHUB_OUTPUT

    - name: Download Ventas task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition ${{ env.TASK_DEF_VENTAS }} \
          --query taskDefinition > task-definition-ventas.json

    - name: Fill in the new image ID in the Amazon ECS task definition for Ventas
      id: task-def-ventas
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition-ventas.json
        container-name: ${{ env.CONTAINER_NAME_VENTAS }}
        image: ${{ steps.build-image-ventas.outputs.image }}

    - name: Deploy Amazon ECS task definition for Ventas
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def-ventas.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_VENTAS }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
        force-new-deployment: true

    - name: Download Despachos task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition ${{ env.TASK_DEF_DESPACHOS }} \
          --query taskDefinition > task-definition-despachos.json

    - name: Fill in the new image ID in the Amazon ECS task definition for Despachos
      id: task-def-despachos
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition-despachos.json
        container-name: ${{ env.CONTAINER_NAME_DESPACHOS }}
        image: ${{ steps.build-image-despachos.outputs.image }}

    - name: Deploy Amazon ECS task definition for Despachos
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def-despachos.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE_DESPACHOS }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
        force-new-deployment: true
